spring.application.name=com.automobile.project

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/automobile_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:vishva}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.manager.username=${MANAGER_USERNAME:manager}
app.manager.password=${MANAGER_PASSWORD:manager123}

server.port=${PORT:8080}